FROM node:18.13.0

ARG ENV_NAME
ARG DOMAIN

ENV ENV_NAME=${ENV_NAME}
ENV DOMAIN=${DOMAIN}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV TZ="Asia/Tokyo"

RUN cd ~ \
    # No root
    && userdel node \
    && groupadd -g 1000 clamav \
    && useradd -d /home/root/ -s /bin/bash -u 1000 -g 1000 clamav \
    && mkdir -p /home/root/ \
    && chown -R clamav:clamav /home/root/ /usr/local/lib/node_modules/ \
    && chmod 775 /home/root/ /usr/local/lib/node_modules/ \
    # Apt
    && apt-get update && apt-get install -y \
    clamav-daemon \
    # ClamAV
    && mkdir /var/run/clamav/ \
    && chown clamav:clamav /var/run/clamav/ /var/lib/clamav/ /run/clamav/ /etc/clamav/ \
    && chmod 775 /var/run/clamav/ /var/lib/clamav/ /run/clamav/ /etc/clamav/ \
    && freshclam \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER clamav

WORKDIR /home/root/

CMD service clamav-daemon restart \
    && service clamav-daemon status \
    && npm install && npm run execute

EXPOSE 1990
