FROM ubuntu:22.04

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIME_ZONE
ARG _LANG
ARG _SERVER_PORT
ARG _PATH_ROOT

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIME_ZONE}
ENV LANG=${_LANG}
ENV SERVER_PORT=${_SERVER_PORT}
ENV PATH_ROOT=${_PATH_ROOT}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV SUDO_FORCE_REMOVE=yes
ENV NODE_OPTIONS=--use-openssl-ca

COPY ./.ms_cronjob-volume/certificate/* /usr/local/share/ca-certificates/
COPY ./docker/NotoSansJP-Regular.ttf /usr/share/fonts/truetype/noto/
COPY ./docker/NotoSansSymbols2-Regular.ttf /usr/share/fonts/truetype/noto/
COPY ./docker/NotoColorEmoji-Regular.ttf /usr/share/fonts/truetype/noto/
COPY ./docker/font.local.conf /etc/fonts/local.conf

RUN cd ~ \
    # No root
    && useradd -U clamav -d ${PATH_ROOT} -s /bin/bash \
    && mkdir -p ${PATH_ROOT} /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    && chown -R clamav:clamav ${PATH_ROOT} /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    && chmod -R 775 ${PATH_ROOT} /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    # Update
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates tzdata curl media-types jq \
    && update-ca-certificates \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone \
    && echo "application/typescript ts" >> /etc/mime.types \
    # NodeJs
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get update && apt-get install -y \
    nodejs \
    # ClamAV
    && apt-get update && apt-get install -y \
    clamav-daemon \
    && freshclam \
    # Clean
    && apt-get remove --purge -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER clamav

WORKDIR ${PATH_ROOT}

CMD \
    # ClamAV
    service clamav-daemon restart \
    && service clamav-daemon status \
    # Npm
    && rm -rf ${PATH_ROOT}node_modules/ ${PATH_ROOT}package-lock.json \
    && npm install \
    && npm run execute

EXPOSE ${SERVER_PORT}
