FROM ubuntu:25.10

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIME_ZONE
ARG _LANG
ARG _SERVER_PORT
ARG _PATH_ROOT
ARG _PATH_CERTIFICATE_PEM

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIME_ZONE}
ENV LANG=${_LANG}
ENV SERVER_PORT=${_SERVER_PORT}
ENV PATH_ROOT=${_PATH_ROOT}
ENV PATH_CERTIFICATE_PEM=${_PATH_CERTIFICATE_PEM}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV SUDO_FORCE_REMOVE=yes
ENV HISTFILE="/home/clamav/.bash_history"
ENV NODE_OPTIONS=--use-openssl-ca
ENV NODE_EXTRA_CA_CERTS="${PATH_CERTIFICATE_PEM}"
ENV NPM_CONFIG_USERCONFIG="/home/clamav/.npmrc"

COPY ./certificate/ /usr/local/share/ca-certificates/
COPY ./docker/font/ /usr/share/fonts/truetype/noto/
COPY ./docker/font.conf /etc/fonts/local.conf

RUN cd ~ \
    # No root
    && userdel -r ubuntu \
    && groupadd -g 1000 clamav \
    && useradd -m -u 1000 -g 1000 -d ${PATH_ROOT} -s /bin/bash clamav \
    && uid="$(id -u clamav)" \
    && mkdir -p ${PATH_ROOT} /home/clamav/ /run/user/${uid} /usr/lib/node_modules/npm/ \
    && chown -R clamav:clamav ${PATH_ROOT} /home/clamav/ /run/user/${uid} /usr/lib/node_modules/npm/ \
    && chmod -R 775 ${PATH_ROOT} /home/clamav/ /usr/lib/node_modules/npm/ \
    && chmod -R 700 /run/user/${uid} \
    # Update
    && echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries \
    && echo 'Acquire::http::No-Cache "true";' > /etc/apt/apt.conf.d/99no-cache \
    && echo 'Acquire::https::No-Cache "true";' >> /etc/apt/apt.conf.d/99no-cache \
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates tzdata curl media-types jq gettext-base \
    && update-ca-certificates \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone \
    && echo "text/typescript ts" >> /etc/mime.types \
    # NodeJs
    && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get update && apt-get install -y \
    nodejs \
    && npm install -g npm@latest \
    && rm -rf /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && mkdir -p /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && curl -fsSL https://registry.npmjs.org/brace-expansion/-/brace-expansion-5.0.8.tgz | tar -xz --strip-components=1 -C /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && rm -rf /usr/lib/node_modules/npm/node_modules/tar \
    && mkdir -p /usr/lib/node_modules/npm/node_modules/tar \
    && curl -fsSL https://registry.npmjs.org/tar/-/tar-7.5.21.tgz | tar -xz --strip-components=1 -C /usr/lib/node_modules/npm/node_modules/tar \
    # ClamAV
    && apt-get update && apt-get install -y \
    clamav-daemon \
    && freshclam \
    && mkdir -p /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    && chown -R clamav:clamav /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    && chmod -R 775 /run/clamav/ /var/run/clamav/ /var/lib/clamav/ /etc/clamav/ \
    # Clean
    && apt-get remove --purge -y sudo \
    && rm -f cuda-keyring_1.1-1_all.deb \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

USER clamav

WORKDIR ${PATH_ROOT}

CMD ["sh", "-c", "bash ${PATH_ROOT}script/clamav.sh && bash ${PATH_ROOT}script/npm.sh 'execute'"]

EXPOSE ${SERVER_PORT}
